<?xml version='1.0' encoding='iso-8859-1' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [ 
  <!ENTITY nbsp "&#160;">
] >

<issue num="2233" status="New">
<title><tt>bad_function_call::what()</tt> unhelpful</title>
<section><sref ref="[func.wrap.badcall]"/></section>
<submitter>Jonathan Wakely</submitter>
<date>5 Jan 2013</date>

<discussion>
<p>
A strict reading of the standard implies <tt>std::bad_function_call{}.what()</tt> returns the same string as
<tt>std::exception{}.what()</tt> which doesn't help to know what happened if you catch an exception by reference 
to <tt>std::exception</tt>.
</p>

<p>
For consistency with <tt>bad_weak_ptr::what()</tt> it should return <tt>"bad_function_call"</tt>.
</p>

<p>
See <a href="http://accu.org/cgi-bin/wg21/message?wg=lib&amp;msg=33515">c++std-lib-33515</a> for other details.
</p>

<p>
There was a considerable support on the reflector to instead change the specification of both <tt>bad_weak_ptr::what()</tt> 
and <tt>bad_function_call::what()</tt> to return an implementation-defined string instead.
</p>
</discussion>

<resolution>
<p>This wording is relative to N3485.</p>

<ol>
<li><p>Edit <sref ref="[func.wrap.badcall.const]"/>:</p>
<blockquote><pre>
bad_function_call() noexcept;
</pre><blockquote>
<p>
-1- <i>Effects</i>: constructs a <tt>bad_function_call object</tt>.
<p/>
<ins>-?- <i>Postconditions</i>: <tt>what()</tt> returns <tt>"bad_function_call"</tt>.</ins>
</p>
</blockquote></blockquote>
</li>
</ol>

</resolution>

</issue>
