<?xml version='1.0' encoding='iso-8859-1' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [ 
  <!ENTITY nbsp "&#160;">
] >

<issue num="1008" status="NAD">
<title><tt>nested_exception</tt> wording unclear</title>
<section><sref ref="[except.nested]"/></section>
<submitter>Alisdair Meredith</submitter>
<date>11 Mar 2009</date>

<discussion>

<p><b>Addresses JP 31</b></p>

<p>
It is difficult to understand in which case <tt>nested_exception</tt> is applied.
</p>

<note>
Summit:
</note>
 
<blockquote><p>
Alisdair will add an example in an update to
<a href="http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2619.pdf">N2619</a>.
</p></blockquote>

<note>
2009-10 Santa Cruz:
</note>

<blockquote><p>
It doesn't appear that N2619 really addresses this. Alisdair to propose wording.
</p></blockquote>

<note>
2010 Pittsburgh:
</note>

<blockquote><p>
Mark issue 1008 as NAD, the type is adequately described.
</p></blockquote>

</discussion>

<rationale>
<p>
nested_exception is intended to be inherited from by exception classes
that are to be thrown during the handling of another exception, i.e.
when translating from one exception type to another. nested_exception
allows the originally thrown exception to be easily retained in that
scenario.
</p>
</rationale>

<resolution>
</resolution>

</issue>
